### ISSUE TITLE
Start local SMTP server

### ISSUE THREAD

**Issue by r-brown** [Labs64/laravel-boilerplate#15]
[SMTP docker](https://hub.docker.com/r/namshi/smtp/) or [MailHog](https://hub.docker.com/r/mailhog/mailhog/) container allows starting of local SMTP server, which can be used for testing purposes.
```
$ docker run -d -p 1025:1025 -p 8025:8025 mailhog/mailhog
```

**Comment by r-brown** [comment]
Docker containers above can be definitely used in a local environment.
However mailtrap.io would be the easiest option to start with.

**Comment by r-brown** [comment]
Verify extraction of the `phpmyadmin` and `mailhog` services in a different compose file; e.g.
```
$ docker-compose -f docker-compose.yml -f docker-compose.utils.yml up -d
```

see also [Share Compose configurations between files and projects](https://docs.docker.com/compose/extends/)

**Comment by r-brown** [comment]
**docker-compose.utils.yml**
```
version: '2'
services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always
```
